site_name: Wave Extensions for ArcGIS / ArcFM
theme: cinder
pages:
- Getting Started:
  - Introduction: index.md
  - Developer Samples: samples.md
- Features: features.md
- Frequently Asked Questions: faq.md
- About:
  - Contributing: contribute.md
  - Release Notes: release-notes.md
