site_name: 'Wave'
site_description: 'C# extensions for ArcFM Solution and ArcGIS for Desktop development.'
site_author: 'Kyle Baesler'
site_url: 'http://jumpercables.github.io/Wave/'

repo_name: 'GitHub'
repo_url: 'https://github.com/Jumpercables/Wave/'

copyright: 'Copyright (c) 2016 Kyle Baesler'

extra:
    version: '1.0.3'
    logo: 'images\wave-red-64.png'
    author:
      github: 'Jumpercables'
    palette:
      primary: 'Red'
      accent: 'Teal'

markdown_extensions:
    - smarty
    - footnotes
    - sane_lists
    - codehilite(css_class=code)
    - admonition
    - toc:
        permalink: '#'

theme: 'material'

pages:
- Home: 'index.md'
- Samples: 'samples.md'
- Features: 'features.md'
- Frequently Asked Questions: 'faq.md'
- About:
  - Contributing: 'contribute.md'
  - Release Notes: 'release-notes.md'
  - License: 'license.md'
- Resources: 'resources.md'
